// extensions/erdos-database-client/src/vue/redis/redisStatus.vue
<template>
  <div id="app">
    <!-- auto refresh row -->
    <el-row>
      <el-col>
        <div style="float: right;">
          <el-tag type="info">
            <i class="el-icon-refresh"></i>
            Auto Refresh
          </el-tag>

          <el-tooltip class="item" effect="dark" :content="'Auto Refresh Switch, Refresh Every 2 Seconds'" placement="bottom">
            <el-switch v-model="autoRefresh" @change="refreshInit">
            </el-switch>
          </el-tooltip>
        </div>
      </el-col>
    </el-row>

    <!-- server status row -->
    <el-row :gutter="10" class="status-container status-card">
      <!-- server -->
      <el-col :span="8">
        <el-card class="box-card">
          <div slot="header" class="clearfix">
            <i class="fa fa-server"></i>
            <span>Server</span>
          </div>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Redis Version:
              <span class="server-status-text">{{this.connectionStatus.redis_version}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              OS:
              <span class="server-status-text" :title="connectionStatus.os">{{this.connectionStatus.os}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Process ID:
              <span class="server-status-text">{{this.connectionStatus.process_id}}</span>
            </el-tag>
          </p>
        </el-card>
      </el-col>

      <!-- memory row -->
      <el-col :span="8">
        <el-card class="box-card">
          <div slot="header" class="clearfix">
            <i class="fa fa-microchip"></i>
            <span> Memory</span>
          </div>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Used Memory:
              <span class="server-status-text">{{this.connectionStatus.used_memory_human}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Used Memory Peak:
              <span class="server-status-text">{{this.connectionStatus.used_memory_peak_human}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Used Memory Lua:
              <span class="server-status-text">{{Math.round(this.connectionStatus.used_memory_lua / 1024)}}K</span>
            </el-tag>
          </p>
        </el-card>
      </el-col>

      <!-- stats row -->
      <el-col :span="8">
        <el-card class="box-card">
          <div slot="header" class="clearfix">
            <i class="fa fa-thermometer-three-quarters"></i>
            <span>Stats</span>
          </div>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Connected Clients:
              <span class="server-status-text">{{this.connectionStatus.connected_clients}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Total Connections:
              <span class="server-status-text">{{this.connectionStatus.total_connections_received}}</span>
            </el-tag>
          </p>

          <p class="server-status-tag-p">
            <el-tag class='server-status-container' type="info" size="big">
              Total Commands:
              <span class="server-status-text">{{this.connectionStatus.total_commands_processed}}</span>
            </el-tag>
          </p>
        </el-card>
      </el-col>
    </el-row>

    <!-- key statistics -->
    <el-row class="status-card">
      <el-col>
        <el-card class="box-card">
          <div slot="header" class="clearfix">
            <i class="fa fa-bar-chart"></i>
            <span>Key Statistics</span>
          </div>

          <el-table :data="DBKeys" stripe>
            <el-table-column fixed prop="db" label="DB">
            </el-table-column>
            <el-table-column sortable prop="keys" label="Keys" :sort-method="sortByKeys">
            </el-table-column>
            <el-table-column sortable prop="expires" label="Expires" :sort-method="sortByExpires">
            </el-table-column>
            <el-table-column sortable prop="avg_ttl" label="Avg TTL" :sort-method="sortByTTL">
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
    </el-row>

    <!-- redis all info -->
    <el-row class="status-card">
      <el-col>
        <el-card class="box-card">
          <div slot="header" class="clearfix">
            <i class="fa fa-info-circle"></i>
            <span> All Redis Info</span>
          </div>

          <el-table :data="AllRedisInfo" stripe>
            <el-table-column fixed prop="key" label="Key">
            </el-table-column>
            <el-table-column prop="value" label="Value">
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
    </el-row>

  </div>
</template>

<script>
import { getVscodeEvent } from "../util/vscode"
let vscodeEvent
export default {
  data() {
    return {
      autoRefresh: false,
      refreshTimer: null,
      refreshInterval: 2000,
      connectionStatus: {},
      statusConnection: null,
    }
  },
  mounted() {
    vscodeEvent = getVscodeEvent()
    this.refreshInit()
    vscodeEvent.on("info", (info) => {
      this.initStatus(info)
    })
    vscodeEvent.emit("route-" + this.$route.name)
  },
  destroyed() {
    clearInterval(this.refreshTimer)
    vscodeEvent.destroy()
  },
  methods: {
    refreshInit() {
      this.refreshTimer=setInterval(() => {
        if (this.autoRefresh) {
          vscodeEvent.emit("route-" + this.$route.name)
        }
      },2000);
    },
    sortByKeys(a, b) {
      return a.keys - b.keys
    },
    sortByExpires(a, b) {
      return a.expires - b.expires
    },
    sortByTTL(a, b) {
      return a.avg_ttl - b.avg_ttl
    },
    initStatus(content) {
      if (!content) {
        return {}
      }

      content = content.split("\n")
      const lines = {}

      for (let i of content) {
        i = i.replace(/\s/gi, "")
        if (i.startsWith("#") || !i) continue

        const kv = i.split(":")
        lines[kv[0]] = kv[1]
      }

      this.connectionStatus = lines
    },
  },
  computed: {
    DBKeys() {
      const dbs = []

      for (const i in this.connectionStatus) {
        if (i.startsWith("db")) {
          const item = this.connectionStatus[i]
          const array = item.split(",")

          dbs.push({
            db: i,
            keys: array[0].split("=")[1],
            expires: array[1].split("=")[1],
            avg_ttl: array[2].split("=")[1],
          })
        }
      }

      return dbs
    },
    AllRedisInfo() {
      const infos = []

      for (const i in this.connectionStatus) {
        infos.push({ key: i, value: this.connectionStatus[i] })
      }

      return infos
    },
  },
}
</script>

<style scoped>
body {
  background-color: #f7f7f7;
  font-family: "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", Arial, sans-serif;
}

.el-row.status-card {
  margin-top: 20px;
}

.server-status-tag-p {
  height: 32px;
}

.server-status-container {
  width: 100%;
  overflow-x: hidden;
  text-overflow: ellipsis;
}

.server-status-text {
  color: #43b50b;
}
</style>

// src/vs/workbench/contrib/erdosDatabaseClient/browser/components/RedisStatus.tsx
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2025 Lotas Inc. All rights reserved.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';
import { useState, useEffect, useCallback, useRef } from 'react';
import { IRedisServerInfo } from '../../common/erdosDatabaseClientApi.js';

interface RedisStatusProps {
    connectionId: string;
    onGetRedisStatus: (connectionId: string) => Promise<IRedisServerInfo>;
    onShowMessage: (message: string, type: 'info' | 'warning' | 'error') => void;
}

interface DBKeyStats {
    db: string;
    keys: number;
    expires: number;
    avg_ttl: number;
}

interface SortField {
    field: 'keys' | 'expires' | 'avg_ttl';
    direction: 'asc' | 'desc';
}

export const RedisStatus: React.FC<RedisStatusProps> = ({
    connectionId,
    onGetRedisStatus,
    onShowMessage
}) => {
    // Main state
    const [redisInfo, setRedisInfo] = useState<IRedisServerInfo>({} as IRedisServerInfo);
    const [loading, setLoading] = useState(false);
    const [autoRefresh, setAutoRefresh] = useState(false);
    const [sortField, setSortField] = useState<SortField>({ field: 'keys', direction: 'desc' });

    // Refs for timers
    const refreshTimer = useRef<number | null>(null);
    const refreshInterval = 2000; // 2 seconds

    // Load Redis status
    const loadRedisStatus = useCallback(async () => {
        if (!connectionId) return;

        setLoading(true);
        try {
            const info = await onGetRedisStatus(connectionId);
            setRedisInfo(info);
        } catch (error: any) {
            onShowMessage(`Redis Status Error: ${error.message}`, 'error');
        } finally {
            setLoading(false);
        }
    }, [connectionId, onGetRedisStatus, onShowMessage]);

    // Auto refresh functionality
    const setupAutoRefresh = useCallback(() => {
        if (refreshTimer.current) {
            window.clearInterval(refreshTimer.current);
            refreshTimer.current = null;
        }

        if (autoRefresh) {
            refreshTimer.current = window.setInterval(() => {
                loadRedisStatus();
            }, refreshInterval);
        }
    }, [autoRefresh, loadRedisStatus]);

    // Handle auto refresh toggle
    const handleAutoRefreshToggle = useCallback((enabled: boolean) => {
        setAutoRefresh(enabled);
    }, []);

    // Parse DB key statistics from Redis info
    const getDBKeys = useCallback((): DBKeyStats[] => {
        const dbs: DBKeyStats[] = [];

        for (const key in redisInfo) {
            if (key.startsWith('db')) {
                const value = redisInfo[key];
                if (typeof value === 'string') {
                    const parts = value.split(',');
                    const keys = parseInt(parts[0]?.split('=')[1] || '0');
                    const expires = parseInt(parts[1]?.split('=')[1] || '0');
                    const avg_ttl = parseInt(parts[2]?.split('=')[1] || '0');

                    dbs.push({
                        db: key,
                        keys,
                        expires,
                        avg_ttl
                    });
                }
            }
        }

        return dbs;
    }, [redisInfo]);

    // Get all Redis info as key-value pairs
    const getAllRedisInfo = useCallback((): Array<{ key: string; value: string }> => {
        const infos: Array<{ key: string; value: string }> = [];

        for (const key in redisInfo) {
            infos.push({ key, value: String(redisInfo[key]) });
        }

        return infos;
    }, [redisInfo]);

    // Sort table by field
    const handleSort = useCallback((field: 'keys' | 'expires' | 'avg_ttl') => {
        setSortField(prev => ({
            field,
            direction: prev.field === field && prev.direction === 'desc' ? 'asc' : 'desc'
        }));
    }, []);

    // Sort DB keys based on current sort field
    const sortedDBKeys = useCallback(() => {
        const dbKeys = getDBKeys();
        
        return dbKeys.sort((a, b) => {
            const aVal = a[sortField.field];
            const bVal = b[sortField.field];
            const result = aVal - bVal;
            return sortField.direction === 'desc' ? -result : result;
        });
    }, [getDBKeys, sortField]);

    // Format memory value for Lua memory
    const formatLuaMemory = useCallback((value: any): string => {
        if (!value) return '-';
        const numValue = typeof value === 'number' ? value : parseInt(String(value));
        return isNaN(numValue) ? '-' : Math.round(numValue / 1024) + 'K';
    }, []);

    // Effects
    useEffect(() => {
        loadRedisStatus();
    }, [loadRedisStatus]);

    useEffect(() => {
        setupAutoRefresh();
        return () => {
            if (refreshTimer.current) {
                window.clearInterval(refreshTimer.current);
            }
        };
    }, [setupAutoRefresh]);

    return (
        <div className={`redis-status ${loading ? 'loading' : ''}`}>
            {/* Auto Refresh Controls */}
            <div className="refresh-controls">
                <div className="auto-refresh">
                    <label>
                        <i className="codicon codicon-refresh"></i>
                        Auto Refresh
                    </label>
                    <input 
                        type="checkbox" 
                        checked={autoRefresh}
                        onChange={(e) => handleAutoRefreshToggle(e.target.checked)}
                    />
                    <span className="refresh-interval">Every 2 seconds</span>
                </div>
            </div>

            {/* Server Status Cards */}
            <div className="status-cards">
                {/* Server Info Card */}
                <div className="status-card">
                    <div className="card-header">
                        <i className="codicon codicon-server"></i>
                        <span>Server</span>
                    </div>
                    <div className="card-content">
                        <div className="status-item">
                            <span className="label">Redis Version:</span>
                            <span className="value">{redisInfo.redis_version || '-'}</span>
                        </div>
                        <div className="status-item">
                            <span className="label">OS:</span>
                            <span className="value" title={redisInfo.os || ''}>
                                {redisInfo.os || '-'}
                            </span>
                        </div>
                        <div className="status-item">
                            <span className="label">Process ID:</span>
                            <span className="value">{redisInfo.process_id || '-'}</span>
                        </div>
                    </div>
                </div>

                {/* Memory Info Card */}
                <div className="status-card">
                    <div className="card-header">
                        <i className="codicon codicon-chip"></i>
                        <span>Memory</span>
                    </div>
                    <div className="card-content">
                        <div className="status-item">
                            <span className="label">Used Memory:</span>
                            <span className="value">{redisInfo.used_memory_human || '-'}</span>
                        </div>
                        <div className="status-item">
                            <span className="label">Used Memory Peak:</span>
                            <span className="value">{redisInfo.used_memory_peak_human || '-'}</span>
                        </div>
                        <div className="status-item">
                            <span className="label">Used Memory Lua:</span>
                            <span className="value">{formatLuaMemory(redisInfo.used_memory_lua)}</span>
                        </div>
                    </div>
                </div>

                {/* Stats Info Card */}
                <div className="status-card">
                    <div className="card-header">
                        <i className="codicon codicon-graph"></i>
                        <span>Stats</span>
                    </div>
                    <div className="card-content">
                        <div className="status-item">
                            <span className="label">Connected Clients:</span>
                            <span className="value">{redisInfo.connected_clients || '-'}</span>
                        </div>
                        <div className="status-item">
                            <span className="label">Total Connections:</span>
                            <span className="value">{redisInfo.total_connections_received || '-'}</span>
                        </div>
                        <div className="status-item">
                            <span className="label">Total Commands:</span>
                            <span className="value">{redisInfo.total_commands_processed || '-'}</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* Key Statistics Table */}
            <div className="status-section">
                <div className="section-header">
                    <i className="codicon codicon-graph-line"></i>
                    <span>Key Statistics</span>
                </div>
                <div className="table-container">
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>DB</th>
                                <th 
                                    className={`sortable ${sortField.field === 'keys' ? `sorted-${sortField.direction}` : ''}`}
                                    onClick={() => handleSort('keys')}
                                >
                                    Keys
                                </th>
                                <th 
                                    className={`sortable ${sortField.field === 'expires' ? `sorted-${sortField.direction}` : ''}`}
                                    onClick={() => handleSort('expires')}
                                >
                                    Expires
                                </th>
                                <th 
                                    className={`sortable ${sortField.field === 'avg_ttl' ? `sorted-${sortField.direction}` : ''}`}
                                    onClick={() => handleSort('avg_ttl')}
                                >
                                    Avg TTL
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {sortedDBKeys().map((stat) => (
                                <tr key={stat.db}>
                                    <td>{stat.db}</td>
                                    <td>{stat.keys}</td>
                                    <td>{stat.expires}</td>
                                    <td>{stat.avg_ttl}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* All Redis Info Table */}
            <div className="status-section">
                <div className="section-header">
                    <i className="codicon codicon-info"></i>
                    <span>All Redis Info</span>
                </div>
                <div className="table-container">
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>Key</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            {getAllRedisInfo().map((info) => (
                                <tr key={info.key}>
                                    <td>{info.key}</td>
                                    <td>{info.value}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};
